### ISSUE TITLE
Update Microsoft.NETCore.UniversalWindowsPlatform to 6.2.3

### ISSUE THREAD

**Issue by harvinders** [Microsoft/WindowsTemplateStudio#2949]
## For Bugs:
The current version of Microsoft.NETCore.UniversalWindowsPlatform 6.1.9 cause issues if we import ReactiveUI package into project. The .net native compiler throws error. If I manually update the package to 6.2.3 it works fine. Ignore if you think ReactiveUI should fix the issue by working with 6.1.9, I can manually update the WTS project.

### Repro steps

1. Create a new WTS project
2. Add latest ReactiveUI package to main project
3. Build release

### Expected Behavior
Compile without errors

### Actual Behavior
Compilation error
```
1>C:\Users\AUser\.nuget\packages\microsoft.net.native.compiler\2.1.8\tools\Microsoft.NetNative.targets(788,5): warning : ILTransform : warning ILT0005: Type 'System.Runtime.CompilerServices.IAsyncStateMachine' from assembly 'System.Runtime' was not included in compilation, but was referenced in method 'BitmapImageBitmap.<Save>d__8.SetStateMachine(IAsyncStateMachine)'. There may have been a missing assembly, or a dependency on a more recent Windows SDK release.
1>C:\Users\AUser\.nuget\packages\microsoft.net.native.compiler\2.1.8\tools\Microsoft.NetNative.targets(788,5): warning : ILTransform : warning ILT0003: Method 'BitmapImageBitmap.<Save>d__8.SetStateMachine(IAsyncStateMachine)' will always throw an exception due to the missing method 'AsyncTaskMethodBuilder.SetStateMachine(IAsyncStateMachine)' in assembly 'System.Threading.Tasks'. There may have been a missing assembly, or a dependency on a more recent Windows SDK release.
1>C:\Users\AUser\.nuget\packages\microsoft.net.native.compiler\2.1.8\tools\Microsoft.NetNative.targets(788,5): warning : ILTransform : warning ILT0003: Method 'DispatcherMixin.<RunTaskAsync>d__0.SetStateMachine(IAsyncStateMachine)' will always throw an exception due to the missing method 'AsyncTaskMethodBuilder<T>.SetStateMachine(IAsyncStateMachine)' in assembly 'System.Threading.Tasks'. There may have been a missing assembly, or a dependency on a more recent Windows SDK release.
1>C:\Users\AUser\.nuget\packages\microsoft.net.native.compiler\2.1.8\tools\Microsoft.NetNative.targets(788,5): warning : ILTransform : warning ILT0003: Method 'WriteableBitmapImageBitmap.<Save>d__9.SetStateMachine(IAsyncStateMachine)' will always throw an exception due to the missing method 'AsyncTaskMethodBuilder.SetStateMachine(IAsyncStateMachine)' in assembly 'System.Threading.Tasks'. There may have been a missing assembly, or a dependency on a more recent Windows SDK release.
1>C:\Users\AUser\.nuget\packages\microsoft.net.native.compiler\2.1.8\tools\Microsoft.NetNative.targets(788,5): warning : ILTransform : warning ILT0003: Method 'DispatcherMixin.<>c__DisplayClass0_0.<<RunTaskAsync>b__0>d.SetStateMachine(IAsyncStateMachine)' will always throw an exception due to the missing method 'AsyncVoidMethodBuilder.SetStateMachine(IAsyncStateMachine)' in assembly 'System.Threading.Tasks'. There may have been a missing assembly, or a dependency on a more recent Windows SDK release.
1>C:\Users\AUser\.nuget\packages\microsoft.net.native.compiler\2.1.8\tools\Microsoft.NetNative.targets(788,5): warning : ILTransform : warning ILT0003: Method 'DispatcherMixin.<>c__DisplayClass1_0.<<RunTaskAsync>b__0>d.SetStateMachine(IAsyncStateMachine)' will always throw an exception due to the missing method 'AsyncTaskMethodBuilder<bool>.SetStateMachine(IAsyncStateMachine)' in assembly 'System.Threading.Tasks'. There may have been a missing assembly, or a dependency on a more recent Windows SDK release.
1>C:\Users\AUser\.nuget\packages\microsoft.net.native.compiler\2.1.8\tools\Microsoft.NetNative.targets(788,5): warning : ILTransform : warning ILT0003: Method 'PlatformBitmapLoader.<>c__DisplayClass0_0.<<Load>b__0>d.SetStateMachine(IAsyncStateMachine)' will always throw an exception due to the missing method 'AsyncTaskMethodBuilder<IBitmap>.SetStateMachine(IAsyncStateMachine)' in assembly 'System.Threading.Tasks'. There may have been a missing assembly, or a dependency on a more recent Windows SDK release.
1>C:\Users\AUser\.nuget\packages\microsoft.net.native.compiler\2.1.8\tools\Microsoft.NetNative.targets(788,5): warning : ILTransform : warning ILT0003: Method 'PlatformBitmapLoader.<>c__DisplayClass1_0.<<LoadFromResource>b__0>d.SetStateMachine(IAsyncStateMachine)' will always throw an exception due to the missing method 'AsyncTaskMethodBuilder<IBitmap>.SetStateMachine(IAsyncStateMachine)' in assembly 'System.Threading.Tasks'. There may have been a missing assembly, or a dependency on a more recent Windows SDK release.
1>C:\Users\AUser\.nuget\packages\microsoft.net.native.compiler\2.1.8\tools\Microsoft.NetNative.targets(788,5): warning : ILTransform : warning ILT0003: Method 'PlatformModeDetector.<>c.<<SearchForAssembly>b__2_2>d.SetStateMachine(IAsyncStateMachine)' will always throw an exception due to the missing method 'AsyncTaskMethodBuilder<string[]>.SetStateMachine(IAsyncStateMachine)' in assembly 'System.Threading.Tasks'. There may have been a missing assembly, or a dependency on a more recent Windows SDK release.
1>  Cleaning up unreferenced code
1>  Generating native code
1>C:\Users\AUser\.nuget\packages\microsoft.net.native.compiler\2.1.8\tools\Microsoft.NetNative.targets(788,5): error : Error: NUTC303E:Internal Compiler Error: No matches found for a constrained call to method 'instance System.Void System.Runtime.CompilerServices.IAsyncStateMachine.MoveNext()' on type 'Splat.WriteableBitmapImageBitmap+<Save>d__9' from assembly 'Splat' while compiling method 'static System.Void System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start<Splat.WriteableBitmapImageBitmap+<Save>d__9>(Splat.WriteableBitmapImageBitmap+<Save>d__9&)'.
1>C:\Users\AUser\.nuget\packages\microsoft.net.native.compiler\2.1.8\tools\Microsoft.NetNative.targets(788,5): error : Type 'System.Runtime.CompilerServices.IAsyncStateMachine' from assembly 'System.Runtime' was not included in compilation, but was referenced in method 'BitmapImageBitmap.<Save>d__8.SetStateMachine(IAsyncStateMachine)'. There may have been a missing assembly, or a dependency on a more recent Windows SDK release.
1>C:\Users\AUser\.nuget\packages\microsoft.net.native.compiler\2.1.8\tools\Microsoft.NetNative.targets(788,5): error : Method 'BitmapImageBitmap.<Save>d__8.SetStateMachine(IAsyncStateMachine)' will always throw an exception due to the missing method 'AsyncTaskMethodBuilder.SetStateMachine(IAsyncStateMachine)' in assembly 'System.Threading.Tasks'. There may have been a missing assembly, or a dependency on a more recent Windows SDK release.
1>C:\Users\AUser\.nuget\packages\microsoft.net.native.compiler\2.1.8\tools\Microsoft.NetNative.targets(788,5): error : Method 'DispatcherMixin.<RunTaskAsync>d__0.SetStateMachine(IAsyncStateMachine)' will always throw an exception due to the missing method 'AsyncTaskMethodBuilder<T>.SetStateMachine(IAsyncStateMachine)' in assembly 'System.Threading.Tasks'. There may have been a missing assembly, or a dependency on a more recent Windows SDK release.
1>C:\Users\AUser\.nuget\packages\microsoft.net.native.compiler\2.1.8\tools\Microsoft.NetNative.targets(788,5): error : Method 'WriteableBitmapImageBitmap.<Save>d__9.SetStateMachine(IAsyncStateMachine)' will always throw an exception due to the missing method 'AsyncTaskMethodBuilder.SetStateMachine(IAsyncStateMachine)' in assembly 'System.Threading.Tasks'. There may have been a missing assembly, or a dependency on a more recent Windows SDK release.
1>C:\Users\AUser\.nuget\packages\microsoft.net.native.compiler\2.1.8\tools\Microsoft.NetNative.targets(788,5): error : Method 'DispatcherMixin.<>c__DisplayClass0_0.<<RunTaskAsync>b__0>d.SetStateMachine(IAsyncStateMachine)' will always throw an exception due to the missing method 'AsyncVoidMethodBuilder.SetStateMachine(IAsyncStateMachine)' in assembly 'System.Threading.Tasks'. There may have been a missing assembly, or a dependency on a more recent Windows SDK release.
1>C:\Users\AUser\.nuget\packages\microsoft.net.native.compiler\2.1.8\tools\Microsoft.NetNative.targets(788,5): error : Method 'DispatcherMixin.<>c__DisplayClass1_0.<<RunTaskAsync>b__0>d.SetStateMachine(IAsyncStateMachine)' will always throw an exception due to the missing method 'AsyncTaskMethodBuilder<bool>.SetStateMachine(IAsyncStateMachine)' in assembly 'System.Threading.Tasks'. There may have been a missing assembly, or a dependency on a more recent Windows SDK release.
1>C:\Users\AUser\.nuget\packages\microsoft.net.native.compiler\2.1.8\tools\Microsoft.NetNative.targets(788,5): error : Method 'PlatformBitmapLoader.<>c__DisplayClass0_0.<<Load>b__0>d.SetStateMachine(IAsyncStateMachine)' will always throw an exception due to the missing method 'AsyncTaskMethodBuilder<IBitmap>.SetStateMachine(IAsyncStateMachine)' in assembly 'System.Threading.Tasks'. There may have been a missing assembly, or a dependency on a more recent Windows SDK release.
1>C:\Users\AUser\.nuget\packages\microsoft.net.native.compiler\2.1.8\tools\Microsoft.NetNative.targets(788,5): error : Method 'PlatformBitmapLoader.<>c__DisplayClass1_0.<<LoadFromResource>b__0>d.SetStateMachine(IAsyncStateMachine)' will always throw an exception due to the missing method 'AsyncTaskMethodBuilder<IBitmap>.SetStateMachine(IAsyncStateMachine)' in assembly 'System.Threading.Tasks'. There may have been a missing assembly, or a dependency on a more recent Windows SDK release.
1>C:\Users\AUser\.nuget\packages\microsoft.net.native.compiler\2.1.8\tools\Microsoft.NetNative.targets(788,5): error : Method 'PlatformModeDetector.<>c.<<SearchForAssembly>b__2_2>d.SetStateMachine(IAsyncStateMachine)' will always throw an exception due to the missing method 'AsyncTaskMethodBuilder<string[]>.SetStateMachine(IAsyncStateMachine)' in assembly 'System.Threading.Tasks'. There may have been a missing assembly, or a dependency on a more recent Windows SDK release.
1>C:\Users\AUser\.nuget\packages\microsoft.net.native.compiler\2.1.8\tools\Microsoft.NetNative.targets(788,5): error : Type 'System.Runtime.CompilerServices.IAsyncStateMachine' from assembly 'System.Runtime' was not included in compilation, but was referenced in method 'BitmapImageBitmap.<Save>d__8.SetStateMachine(IAsyncStateMachine)'. There may have been a missing assembly, or a dependency on a more recent Windows SDK release.
1>C:\Users\AUser\.nuget\packages\microsoft.net.native.compiler\2.1.8\tools\Microsoft.NetNative.targets(788,5): error : Method 'BitmapImageBitmap.<Save>d__8.SetStateMachine(IAsyncStateMachine)' will always throw an exception due to the missing method 'AsyncTaskMethodBuilder.SetStateMachine(IAsyncStateMachine)' in assembly 'System.Threading.Tasks'. There may have been a missing assembly, or a dependency on a more recent Windows SDK release.
1>C:\Users\AUser\.nuget\packages\microsoft.net.native.compiler\2.1.8\tools\Microsoft.NetNative.targets(788,5): error : Method 'DispatcherMixin.<RunTaskAsync>d__0.SetStateMachine(IAsyncStateMachine)' will always throw an exception due to the missing method 'AsyncTaskMethodBuilder<T>.SetStateMachine(IAsyncStateMachine)' in assembly 'System.Threading.Tasks'. There may have been a missing assembly, or a dependency on a more recent Windows SDK release.
1>C:\Users\AUser\.nuget\packages\microsoft.net.native.compiler\2.1.8\tools\Microsoft.NetNative.targets(788,5): error : Method 'WriteableBitmapImageBitmap.<Save>d__9.SetStateMachine(IAsyncStateMachine)' will always throw an exception due to the missing method 'AsyncTaskMethodBuilder.SetStateMachine(IAsyncStateMachine)' in assembly 'System.Threading.Tasks'. There may have been a missing assembly, or a dependency on a more recent Windows SDK release.
1>C:\Users\AUser\.nuget\packages\microsoft.net.native.compiler\2.1.8\tools\Microsoft.NetNative.targets(788,5): error : Method 'DispatcherMixin.<>c__DisplayClass0_0.<<RunTaskAsync>b__0>d.SetStateMachine(IAsyncStateMachine)' will always throw an exception due to the missing method 'AsyncVoidMethodBuilder.SetStateMachine(IAsyncStateMachine)' in assembly 'System.Threading.Tasks'. There may have been a missing assembly, or a dependency on a more recent Windows SDK release.
1>C:\Users\AUser\.nuget\packages\microsoft.net.native.compiler\2.1.8\tools\Microsoft.NetNative.targets(788,5): error : Method 'DispatcherMixin.<>c__DisplayClass1_0.<<RunTaskAsync>b__0>d.SetStateMachine(IAsyncStateMachine)' will always throw an exception due to the missing method 'AsyncTaskMethodBuilder<bool>.SetStateMachine(IAsyncStateMachine)' in assembly 'System.Threading.Tasks'. There may have been a missing assembly, or a dependency on a more recent Windows SDK release.
1>C:\Users\AUser\.nuget\packages\microsoft.net.native.compiler\2.1.8\tools\Microsoft.NetNative.targets(788,5): error : Method 'PlatformBitmapLoader.<>c__DisplayClass0_0.<<Load>b__0>d.SetStateMachine(IAsyncStateMachine)' will always throw an exception due to the missing method 'AsyncTaskMethodBuilder<IBitmap>.SetStateMachine(IAsyncStateMachine)' in assembly 'System.Threading.Tasks'. There may have been a missing assembly, or a dependency on a more recent Windows SDK release.
1>C:\Users\AUser\.nuget\packages\microsoft.net.native.compiler\2.1.8\tools\Microsoft.NetNative.targets(788,5): error : Method 'PlatformBitmapLoader.<>c__DisplayClass1_0.<<LoadFromResource>b__0>d.SetStateMachine(IAsyncStateMachine)' will always throw an exception due to the missing method 'AsyncTaskMethodBuilder<IBitmap>.SetStateMachine(IAsyncStateMachine)' in assembly 'System.Threading.Tasks'. There may have been a missing assembly, or a dependency on a more recent Windows SDK release.
1>C:\Users\AUser\.nuget\packages\microsoft.net.native.compiler\2.1.8\tools\Microsoft.NetNative.targets(788,5): error : Method 'PlatformModeDetector.<>c.<<SearchForAssembly>b__2_2>d.SetStateMachine(IAsyncStateMachine)' will always throw an exception due to the missing method 'AsyncTaskMethodBuilder<string[]>.SetStateMachine(IAsyncStateMachine)' in assembly 'System.Threading.Tasks'. There may have been a missing assembly, or a dependency on a more recent Windows SDK release.
1>C:\Users\AUser\.nuget\packages\microsoft.net.native.compiler\2.1.8\tools\Microsoft.NetNative.targets(788,5): error : ILT0005: 'C:\Users\AUser\.nuget\packages\runtime.win10-x86.microsoft.net.native.compiler\2.1.8\tools\x86\ilc\Tools\nutc_driver.exe @"C:\Users\AUser\source\repos\App1\App1\obj\x86\Release\ilc\intermediate\MDIL\App1.rsp"' returned exit code 1

```

## System

* **VS Version:** 2017 15.9.7
* **WTS Wizard Version:**3.0.19038.1
* **WTS Template Version:**3.0.19038.1
* **Windows Build:**1803

**Comment by sibille** [comment]
Microsoft.NETCore.UniversalWindowsPlatform version 6.2.3 is not yet available on nuget.org. We cannot update until it is available there, because users that use older versions of VS will not have it available.

**Comment by sibille** [comment]
@harvinders, version 6.2.8 is out, we'll update our templates to this version, see #3037 in WTS 3.1.
